# Generated by Django 4.1.5 on 2023-01-25 11:19

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title ')),
                ('header_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date ')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text')),
                ('category', models.CharField(choices=[('tanks', 'tanks'), ('healers', 'healers'), ('damage dealers', 'damage dealers'), ('merchants', 'merchants'), ('guild masters', 'guild masters'), ('questgivers', 'questgivers'), ('blacksmiths', 'blacksmiths'), ('leatherworkers', 'leatherworkers'), ('potions makers', 'potions makers'), ('spell masters', 'spell masters')], default='tanks', max_length=20)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент отклика')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('status_del', models.BooleanField(default=False, verbose_name='Статус отклика - отклонен')),
                ('status_add', models.BooleanField(default=False, verbose_name='Статус отклика - принят')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamesite.note', verbose_name='Объявление')),
                ('user_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика')),
            ],
        ),
        migrations.DeleteModel(
            name='Gamesite',
        ),
    ]
